parameters:
    app.path.news_images: /uploads/images/news

vich_uploader:
    db_driver: orm

    mappings:
        news_images:
            uri_prefix: /uploads/images/news
            upload_destination: '%kernel.project_dir%/public/uploads/images/news'
